version: '3.4'

services:
  easypeasybox.frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx  
    ports:
      - "80"
      - "443"
    volumes:
       - ~/.aspnet/https:/https:ro
  easypeasybox.backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


